In [1]:
import numpy as np

In [2]:
l= [1,2,3,5,46,8]

In [3]:
ar = np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([ 1,  2,  3,  5, 46,  8])

In [7]:
a=[2,3,4]

In [8]:
np.asanyarray(a)

array([2, 3, 4])

In [9]:
 b=np.matrix(l)

In [10]:
b

matrix([[ 1,  2,  3,  5, 46,  8]])

In [11]:
a= np.array(l)

In [12]:
a

array([ 1,  2,  3,  5, 46,  8])

In [13]:
c= a

In [14]:
c

array([ 1,  2,  3,  5, 46,  8])

In [15]:
a

array([ 1,  2,  3,  5, 46,  8])

In [16]:
c[0]=100 #this process is known as solo copy

In [17]:
c

array([100,   2,   3,   5,  46,   8])

In [18]:
a

array([100,   2,   3,   5,  46,   8])

In [19]:
d= np.copy(a)  #this allocate data in a new way.   and this is also known deep copy

In [20]:
a[1]=400

In [21]:
a

array([100, 400,   3,   5,  46,   8])

In [22]:
d

array([100,   2,   3,   5,  46,   8])

In [23]:
np.fromfunction(lambda i,j : i ==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.fromfunction(lambda i,j : i *j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
iterable=(i*i for i in range(5))

In [26]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [27]:
np.fromstring('23 33',sep=' ')

array([23., 33.])

In [28]:
np.fromstring('4,5', sep=',')

array([4., 5.])

In [29]:
#numpy data types

In [30]:
l=[1,2,3,4,5]

In [31]:
ar= np.array(l)

In [32]:
ar

array([1, 2, 3, 4, 5])

In [33]:
ar.ndim

1

In [34]:
ar2= np.array([[1,2,3,4,7],[1,2,3,4,5]])

In [35]:
ar2

array([[1, 2, 3, 4, 7],
       [1, 2, 3, 4, 5]])

In [36]:
ar2.ndim   #this is for check the dimenstion for array

2

In [37]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [38]:
iterable =(i*i for i in range((5)))

In [39]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [40]:
ar.ndim

1

In [41]:
ar2.ndim

2

In [42]:
ar.size  #for check size in array

5

In [43]:
ar2.size

10

In [44]:
ar2

array([[1, 2, 3, 4, 7],
       [1, 2, 3, 4, 5]])

In [45]:
ar.shape #for checking shape

(5,)

In [46]:
ar2.shape

(2, 5)

In [47]:
ar.dtype

dtype('int32')

In [48]:
ar2.dtype

dtype('int32')

In [49]:
ar22 = np.array([(1.4,25,45), (23,45,66)])

In [50]:
ar22

array([[ 1.4, 25. , 45. ],
       [23. , 45. , 66. ]])

In [51]:
ar22.dtype

dtype('float64')

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [53]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [54]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [55]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [56]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
ar4=np.zeros((3,4,2))

In [59]:
ar4.ndim

3

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
on=np.ones((2,2,2))#like ones and zeros there no more function is avilable

In [62]:
on+5

array([[[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]]])

In [63]:
on+6

array([[[7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.]]])

In [64]:
on+10

array([[[11., 11.],
        [11., 11.]],

       [[11., 11.],
        [11., 11.]]])

In [65]:
on*4

array([[[4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.]]])

In [66]:
np.empty((3,4))

array([[1.22369366e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.15060809e-062, 1.58871371e-076,
        5.48785168e+174],
       [6.95237932e-042, 2.67653030e+184, 1.20858881e+161,
        1.27970364e+161]])

In [67]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [69]:
np.logspace(2,5,10, base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [70]:
arr = np.random.randn(3,4)

In [71]:
import pandas as pd

In [72]:
pd.DataFrame(arr)

0         1         2         3
0  0.805893 -1.273461 -1.203737 -0.963884
1 -0.539102 -1.750293 -0.621438  1.434281
2 -0.608447  0.736443 -0.354135  1.504411

In [73]:
np.random.rand(3,4)

array([[0.3725792 , 0.85441208, 0.04201866, 0.26052831],
       [0.40674641, 0.36504038, 0.36291578, 0.72752115],
       [0.09097501, 0.25492465, 0.47840682, 0.14643672]])

In [74]:
np.random.rand(3,4)

array([[0.6443593 , 0.70645589, 0.59338167, 0.12929235],
       [0.19646824, 0.35960419, 0.32000242, 0.86261336],
       [0.29990037, 0.18685509, 0.15253136, 0.23500762]])

In [75]:
ultimate=np.random.randint(3,110,(300,400))

In [76]:
pd.DataFrame(ultimate)

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    107   19   21   44   51   22    9   35   92   59  ...  108   84   37   
1     86   73   76   83   73  103   59  108  105   31  ...   89   87   81   
2      3   81   81   72   46   84   46   12   20  105  ...    6   77   92   
3      5   12   39   43   11   80   84   93   42   44  ...   45   30   56   
4     24    9   85   68   52   93   28   95   36   49  ...   29   98   65   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   75   69   76   57   51   63   21   14   46   61  ...   29   24   27   
296   57   78   69    7   77   31   75   60   47   51  ...   83  101   21   
297   93   25   10   71   67   38   32   55   25   34  ...    7   52   86   
298   24   36   53    6   79   31   24   22    7   98  ...   83    9   46   
299   64   91   48   71  102   30   91   67    3   48  ...   68   42    8   

     393  394  395  396  397  398  399  
0     77  107   37   54   80    5    4  
1     19   30  102   26   32   37   55  
2     35   52   62    5   28   21   90  
3     65   33   24   35   12  108  105  
4    103   92   30   41   23   69   70  
..   ...  ...  ...  ...  ...  ...  ...  
295   35   55   15   13    6   44   38  
296  100   34   68   96   21    4   62  
297   27   48   28  100   86   67   74  
298   48   27   40   59   15   71   99  
299   64   64  109   10   21   96   14  

[300 rows x 400 columns]

In [77]:
pd.DataFrame(ultimate).to_csv('test.csv')

In [78]:
arr= np.random.rand(3,4)

In [79]:
arr

array([[0.9830104 , 0.1117468 , 0.04344833, 0.6231787 ],
       [0.18509661, 0.26315584, 0.02880242, 0.09489229],
       [0.84273992, 0.45048058, 0.81545844, 0.84345896]])

In [80]:
arr1=arr.reshape(6,2)  #this is basically rearange the data

In [81]:
arr1[1][1]

0.6231787037690795

In [82]:
arr1[2:5,1]

array([0.26315584, 0.09489229, 0.45048058])

In [83]:
arr =np.random.randint(1,100,(5,5))

In [84]:
arr

array([[91, 36, 73, 77, 61],
       [28, 44, 84, 25, 37],
       [22, 54, 35, 60, 45],
       [46, 24, 94, 87, 78],
       [99,  7, 23, 17, 35]])

In [85]:
arr[arr>50]

array([91, 73, 77, 61, 84, 54, 60, 94, 87, 78, 99])

In [86]:
arr

array([[91, 36, 73, 77, 61],
       [28, 44, 84, 25, 37],
       [22, 54, 35, 60, 45],
       [46, 24, 94, 87, 78],
       [99,  7, 23, 17, 35]])

In [87]:
arr[2:4,[1,2]]

array([[54, 35],
       [24, 94]])

In [88]:
arr[0][0]=5000

In [89]:
arr

array([[5000,   36,   73,   77,   61],
       [  28,   44,   84,   25,   37],
       [  22,   54,   35,   60,   45],
       [  46,   24,   94,   87,   78],
       [  99,    7,   23,   17,   35]])

In [90]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [91]:
arr2

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [92]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [93]:
arr1+arr2

array([[3, 2, 3],
       [3, 4, 2],
       [3, 3, 3]])

In [94]:
arr1*arr2

array([[2, 1, 2],
       [2, 4, 1],
       [2, 2, 2]])

In [95]:
arr1-arr2

array([[-1,  0,  1],
       [ 1,  0,  0],
       [-1, -1,  1]])

In [96]:
arr1/arr2

array([[0.5, 1. , 2. ],
       [2. , 1. , 1. ],
       [0.5, 0.5, 2. ]])

In [97]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [98]:
arr2

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [99]:
arr1@arr2 #this is used for matrix multipuction

array([[7, 7, 4],
       [8, 8, 5],
       [7, 7, 4]])

In [100]:
arr1/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_19392\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [101]:
arr1+100

array([[101, 101, 102],
       [102, 102, 101],
       [101, 101, 102]])

In [102]:
arr1**2

array([[1, 1, 4],
       [4, 4, 1],
       [1, 1, 4]])

In [103]:
#braodcastion in case of numpy

In [104]:
arr=np.zeros((4,4))

In [105]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
row =np.array([1,2,3,4])

In [107]:
row

array([1, 2, 3, 4])

In [108]:
arr= row

In [109]:
arr+row

array([2, 4, 6, 8])

In [110]:
row.T

array([1, 2, 3, 4])

In [113]:
row.T

array([1, 2, 3, 4])

In [114]:
at=np.zeros((4,4))

In [115]:
at+23

array([[23., 23., 23., 23.],
       [23., 23., 23., 23.],
       [23., 23., 23., 23.],
       [23., 23., 23., 23.]])